services:
  postgres:
    image: 'postgres:18.3-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - banking
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  banking:
    driver: bridge

volumes:
  db-data:
    driver: local